; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L039\L039\L039.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5675	DB	'hi,%d %d %d %d', 00H
	ORG $+1
$SG5687	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_vsnprintf
PUBLIC	_snprintf
PUBLIC	?f@@YAXXZ					; f
PUBLIC	?f1@@YAXH@Z					; f1
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	_puts:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	___stdio_common_vsprintf:PROC
EXTRN	__alloca_probe_16:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L039\L039\L039.cpp
; Line 25
	push	ebp
	mov	ebp, esp
; Line 26
	push	OFFSET $SG5687
	call	_printf
	add	esp, 4
; Line 27
	push	5
	call	?f1@@YAXH@Z				; f1
	add	esp, 4
; Line 41
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = -12						; size = 4
tv67 = -8						; size = 4
_i$1 = -4						; size = 4
_size$ = 8						; size = 4
?f1@@YAXH@Z PROC					; f1
; File C:\Users\libit\source\repos\L039\L039\L039.cpp
; Line 16
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 17
	mov	eax, DWORD PTR _size$[ebp]
	shl	eax, 2
	call	__alloca_probe_16
	mov	DWORD PTR tv67[ebp], esp
	mov	eax, DWORD PTR tv67[ebp]
	mov	DWORD PTR _a$[ebp], eax
; Line 18
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@f1
$LN2@f1:
	mov	ecx, DWORD PTR _i$1[ebp]
	add	ecx, 1
	mov	DWORD PTR _i$1[ebp], ecx
$LN4@f1:
	mov	edx, DWORD PTR _i$1[ebp]
	cmp	edx, DWORD PTR _size$[ebp]
	jae	SHORT $LN1@f1
; Line 20
	mov	eax, DWORD PTR _i$1[ebp]
	shl	eax, 1
	mov	ecx, DWORD PTR _i$1[ebp]
	mov	edx, DWORD PTR _a$[ebp]
	mov	DWORD PTR [edx+ecx*4], eax
; Line 21
	jmp	SHORT $LN2@f1
$LN1@f1:
; Line 22
	lea	esp, DWORD PTR [ebp-12]
	mov	esp, ebp
	pop	ebp
	ret	0
?f1@@YAXH@Z ENDP					; f1
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv66 = -8						; size = 4
_buffer$ = -4						; size = 4
?f@@YAXXZ PROC						; f
; File C:\Users\libit\source\repos\L039\L039\L039.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 10
	mov	eax, 600				; 00000258H
	call	__alloca_probe_16
	mov	DWORD PTR tv66[ebp], esp
	mov	eax, DWORD PTR tv66[ebp]
	mov	DWORD PTR _buffer$[ebp], eax
; Line 11
	push	4
	push	3
	push	2
	push	1
	push	OFFSET $SG5675
	push	600					; 00000258H
	mov	ecx, DWORD PTR _buffer$[ebp]
	push	ecx
	call	_snprintf
	add	esp, 28					; 0000001cH
; Line 12
	mov	edx, DWORD PTR _buffer$[ebp]
	push	edx
	call	_puts
	add	esp, 4
; Line 13
	lea	esp, DWORD PTR [ebp-8]
	mov	esp, ebp
	pop	ebp
	ret	0
?f@@YAXXZ ENDP						; f
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _snprintf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
_snprintf PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 1948
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 1951
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 1953
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __BufferCount$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Buffer$[ebp]
	push	ecx
	call	_vsnprintf
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 1954
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 1955
	mov	eax, DWORD PTR __Result$[ebp]
; Line 1956
	mov	esp, ebp
	pop	ebp
	ret	0
_snprintf ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vsnprintf
_TEXT	SEGMENT
tv74 = -8						; size = 4
__Result$ = -4						; size = 4
__Buffer$ = 8						; size = 4
__BufferCount$ = 12					; size = 4
__Format$ = 16						; size = 4
__ArgList$ = 20						; size = 4
_vsnprintf PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 1439
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 1440
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	push	0
	mov	ecx, DWORD PTR __Format$[ebp]
	push	ecx
	mov	edx, DWORD PTR __BufferCount$[ebp]
	push	edx
	mov	eax, DWORD PTR __Buffer$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax]
	or	ecx, 2
	mov	edx, DWORD PTR [eax+4]
	push	edx
	push	ecx
	call	___stdio_common_vsprintf
	add	esp, 28					; 0000001cH
	mov	DWORD PTR __Result$[ebp], eax
; Line 1444
	cmp	DWORD PTR __Result$[ebp], 0
	jge	SHORT $LN3@vsnprintf
	mov	DWORD PTR tv74[ebp], -1
	jmp	SHORT $LN4@vsnprintf
$LN3@vsnprintf:
	mov	eax, DWORD PTR __Result$[ebp]
	mov	DWORD PTR tv74[ebp], eax
$LN4@vsnprintf:
	mov	eax, DWORD PTR tv74[ebp]
; Line 1445
	mov	esp, ebp
	pop	ebp
	ret	0
_vsnprintf ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
