; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L046\L046\L046.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5571	DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG5572	DB	'my_abs', 0aH, 00H
$SG5573	DB	'%f', 0aH, 00H
$SG5574	DB	'%f', 0aH, 00H
$SG5575	DB	'set_sign', 0aH, 00H
	ORG $+2
$SG5576	DB	'%f', 0aH, 00H
$SG5577	DB	'%f', 0aH, 00H
$SG5578	DB	'set_neg', 0aH, 00H
	ORG $+3
$SG5579	DB	'%f', 0aH, 00H
$SG5580	DB	'%f', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?my_abs@@YAMM@Z					; my_abs
PUBLIC	?set_sign@@YAMM@Z				; set_sign
PUBLIC	?set_neg@@YAMM@Z				; set_neg
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	__real@42f6e979
PUBLIC	__real@c2f6e979
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	__fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT __real@c2f6e979
CONST	SEGMENT
__real@c2f6e979 DD 0c2f6e979r			; -123.456
CONST	ENDS
;	COMDAT __real@42f6e979
CONST	SEGMENT
__real@42f6e979 DD 042f6e979r			; 123.456
CONST	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L046\L046\L046.cpp
; Line 26
	push	ebp
	mov	ebp, esp
; Line 27
	push	OFFSET $SG5571
	call	_printf
	add	esp, 4
; Line 28
	push	OFFSET $SG5572
	call	_printf
; Line 29
	movss	xmm0, DWORD PTR __real@42f6e979
	movss	DWORD PTR [esp], xmm0
	call	?my_abs@@YAMM@Z				; my_abs
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5573
	call	_printf
; Line 30
	add	esp, 8
	movss	xmm0, DWORD PTR __real@c2f6e979
	movss	DWORD PTR [esp], xmm0
	call	?my_abs@@YAMM@Z				; my_abs
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5574
	call	_printf
	add	esp, 12					; 0000000cH
; Line 32
	push	OFFSET $SG5575
	call	_printf
; Line 33
	movss	xmm0, DWORD PTR __real@42f6e979
	movss	DWORD PTR [esp], xmm0
	call	?set_sign@@YAMM@Z			; set_sign
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5576
	call	_printf
; Line 34
	add	esp, 8
	movss	xmm0, DWORD PTR __real@c2f6e979
	movss	DWORD PTR [esp], xmm0
	call	?set_sign@@YAMM@Z			; set_sign
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5577
	call	_printf
	add	esp, 12					; 0000000cH
; Line 36
	push	OFFSET $SG5578
	call	_printf
; Line 37
	movss	xmm0, DWORD PTR __real@42f6e979
	movss	DWORD PTR [esp], xmm0
	call	?set_neg@@YAMM@Z			; set_neg
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5579
	call	_printf
; Line 38
	add	esp, 8
	movss	xmm0, DWORD PTR __real@c2f6e979
	movss	DWORD PTR [esp], xmm0
	call	?set_neg@@YAMM@Z			; set_neg
	add	esp, -4					; fffffffcH
	fstp	QWORD PTR [esp]
	push	OFFSET $SG5580
	call	_printf
	add	esp, 12					; 0000000cH
; Line 39
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_temp$ = -4						; size = 4
_i$ = 8							; size = 4
?set_neg@@YAMM@Z PROC					; set_neg
; File C:\Users\libit\source\repos\L046\L046\L046.cpp
; Line 19
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 20
	mov	eax, DWORD PTR _i$[ebp]
	xor	eax, -2147483648			; 80000000H
	mov	DWORD PTR _temp$[ebp], eax
; Line 21
	fld	DWORD PTR _temp$[ebp]
; Line 22
	mov	esp, ebp
	pop	ebp
	ret	0
?set_neg@@YAMM@Z ENDP					; set_neg
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_temp$ = -4						; size = 4
_i$ = 8							; size = 4
?set_sign@@YAMM@Z PROC					; set_sign
; File C:\Users\libit\source\repos\L046\L046\L046.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 14
	mov	eax, DWORD PTR _i$[ebp]
	or	eax, -2147483648			; 80000000H
	mov	DWORD PTR _temp$[ebp], eax
; Line 15
	fld	DWORD PTR _temp$[ebp]
; Line 16
	mov	esp, ebp
	pop	ebp
	ret	0
?set_sign@@YAMM@Z ENDP					; set_sign
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_temp$ = -4						; size = 4
_i$ = 8							; size = 4
?my_abs@@YAMM@Z PROC					; my_abs
; File C:\Users\libit\source\repos\L046\L046\L046.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 8
	mov	eax, DWORD PTR _i$[ebp]
	and	eax, 2147483647				; 7fffffffH
	mov	DWORD PTR _temp$[ebp], eax
; Line 9
	fld	DWORD PTR _temp$[ebp]
; Line 10
	mov	esp, ebp
	pop	ebp
	ret	0
?my_abs@@YAMM@Z ENDP					; my_abs
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
