; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L025\L025\L025.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5557	DB	'1,2,7,10', 00H
	ORG $+3
$SG5559	DB	'3', 0a1H, 0a2H, '4', 0a1H, 0a2H, '100', 00H
	ORG $+2
$SG5561	DB	'5,6', 00H
$SG5563	DB	'8', 0a1H, 0a2H, '9', 0a1H, 0a2H, '20', 0a1H, 0a2H, '21', 00H
	ORG $+3
$SG5565	DB	'22', 00H
	ORG $+1
$SG5567	DB	'default', 00H
$SG5570	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?f@@YAXH@Z					; f
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L025\L025\L025.cpp
; Line 41
	push	ebp
	mov	ebp, esp
; Line 42
	push	OFFSET $SG5570
	call	_printf
	add	esp, 4
; Line 43
	push	2
	call	?f@@YAXH@Z				; f
	add	esp, 4
; Line 44
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv64 = -4						; size = 4
_a$ = 8							; size = 4
?f@@YAXH@Z PROC						; f
; File C:\Users\libit\source\repos\L025\L025\L025.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 8
	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 21			; 00000015H
	jg	SHORT $LN11@f
	cmp	DWORD PTR tv64[ebp], 20			; 00000014H
	jge	SHORT $LN7@f
	mov	ecx, DWORD PTR tv64[ebp]
	sub	ecx, 1
	mov	DWORD PTR tv64[ebp], ecx
	cmp	DWORD PTR tv64[ebp], 9
	ja	SHORT $LN9@f
	mov	edx, DWORD PTR tv64[ebp]
	movzx	eax, BYTE PTR $LN12@f[edx]
	jmp	DWORD PTR $LN13@f[eax*4]
$LN11@f:
	cmp	DWORD PTR tv64[ebp], 22			; 00000016H
	je	SHORT $LN8@f
	cmp	DWORD PTR tv64[ebp], 10000		; 00002710H
	je	SHORT $LN5@f
	jmp	SHORT $LN9@f
$LN4@f:
; Line 14
	push	OFFSET $SG5557
	call	_printf
	add	esp, 4
; Line 15
	jmp	SHORT $LN1@f
$LN5@f:
; Line 19
	push	OFFSET $SG5559
	call	_printf
	add	esp, 4
; Line 20
	jmp	SHORT $LN1@f
$LN6@f:
; Line 23
	push	OFFSET $SG5561
	call	_printf
	add	esp, 4
; Line 24
	jmp	SHORT $LN1@f
$LN7@f:
; Line 29
	push	OFFSET $SG5563
	call	_printf
	add	esp, 4
; Line 30
	jmp	SHORT $LN1@f
$LN8@f:
; Line 32
	push	OFFSET $SG5565
	call	_printf
	add	esp, 4
; Line 33
	jmp	SHORT $LN1@f
$LN9@f:
; Line 35
	push	OFFSET $SG5567
	call	_printf
	add	esp, 4
$LN1@f:
; Line 38
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN13@f:
	DD	$LN4@f
	DD	$LN5@f
	DD	$LN6@f
	DD	$LN7@f
$LN12@f:
	DB	0
	DB	0
	DB	1
	DB	1
	DB	2
	DB	2
	DB	0
	DB	3
	DB	3
	DB	0
?f@@YAXH@Z ENDP						; f
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
