; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L048\L048\L048.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5559	DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG5560	DB	'%d', 0aH, 00H
$SG5561	DB	'%d', 0aH, 00H
$SG5562	DB	'%d', 0aH, 00H
$SG5563	DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?my_srand@@YAXI@Z				; my_srand
PUBLIC	?my_rand@@YAHXZ					; my_rand
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
_BSS	SEGMENT
?rand_state@@3IA DD 01H DUP (?)				; rand_state
_BSS	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 26
	push	OFFSET $SG5559
	call	_printf
; Line 28
	push	679057014				; 28799676H
	push	OFFSET $SG5560
; Line 19
	mov	DWORD PTR ?rand_state@@3IA, 679057014	; 28799676H
; Line 28
	call	_printf
; Line 18
	imul	eax, DWORD PTR ?rand_state@@3IA, 1664525
; Line 19
	add	eax, 1513969631				; 5a3d57dfH
; Line 29
	push	eax
	push	OFFSET $SG5561
; Line 19
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 29
	call	_printf
; Line 18
	imul	eax, DWORD PTR ?rand_state@@3IA, 1664525
; Line 19
	add	eax, 1513969631				; 5a3d57dfH
; Line 30
	push	eax
	push	OFFSET $SG5562
; Line 19
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 30
	call	_printf
; Line 18
	imul	eax, DWORD PTR ?rand_state@@3IA, 1664525
; Line 19
	add	eax, 1513969631				; 5a3d57dfH
; Line 31
	push	eax
	push	OFFSET $SG5563
; Line 19
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 31
	call	_printf
	add	esp, 36					; 00000024H
; Line 32
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?my_rand@@YAHXZ PROC					; my_rand
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 18
	imul	eax, DWORD PTR ?rand_state@@3IA, 1664525
; Line 19
	add	eax, 1513969631				; 5a3d57dfH
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 22
	ret	0
?my_rand@@YAHXZ ENDP					; my_rand
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_init$ = 8						; size = 4
?my_srand@@YAXI@Z PROC					; my_srand
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 13
	mov	eax, DWORD PTR _init$[esp-4]
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 14
	ret	0
?my_srand@@YAXI@Z ENDP					; my_srand
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	esi
; Line 958
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 643
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 960
	pop	esi
; Line 961
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 643
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
