; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L048\L048\L048.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5559	DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG5560	DB	'%d', 0aH, 00H
$SG5561	DB	'%d', 0aH, 00H
$SG5562	DB	'%d', 0aH, 00H
$SG5563	DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?my_srand@@YAXI@Z				; my_srand
PUBLIC	?my_rand@@YAHXZ					; my_rand
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
_BSS	SEGMENT
?rand_state@@3IA DD 01H DUP (?)				; rand_state
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 25
	push	ebp
	mov	ebp, esp
; Line 26
	push	OFFSET $SG5559
	call	_printf
	add	esp, 4
; Line 27
	push	4659					; 00001233H
	call	?my_srand@@YAXI@Z			; my_srand
	add	esp, 4
; Line 28
	call	?my_rand@@YAHXZ				; my_rand
	push	eax
	push	OFFSET $SG5560
	call	_printf
	add	esp, 8
; Line 29
	call	?my_rand@@YAHXZ				; my_rand
	push	eax
	push	OFFSET $SG5561
	call	_printf
	add	esp, 8
; Line 30
	call	?my_rand@@YAHXZ				; my_rand
	push	eax
	push	OFFSET $SG5562
	call	_printf
	add	esp, 8
; Line 31
	call	?my_rand@@YAHXZ				; my_rand
	push	eax
	push	OFFSET $SG5563
	call	_printf
	add	esp, 8
; Line 32
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
?my_rand@@YAHXZ PROC					; my_rand
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 17
	push	ebp
	mov	ebp, esp
; Line 18
	imul	eax, DWORD PTR ?rand_state@@3IA, 1664525
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 19
	mov	ecx, DWORD PTR ?rand_state@@3IA
	add	ecx, 1513969631				; 5a3d57dfH
	mov	DWORD PTR ?rand_state@@3IA, ecx
; Line 21
	mov	eax, DWORD PTR ?rand_state@@3IA
; Line 22
	pop	ebp
	ret	0
?my_rand@@YAHXZ ENDP					; my_rand
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_init$ = 8						; size = 4
?my_srand@@YAXI@Z PROC					; my_srand
; File C:\Users\libit\source\repos\L048\L048\L048.cpp
; Line 12
	push	ebp
	mov	ebp, esp
; Line 13
	mov	eax, DWORD PTR _init$[ebp]
	mov	DWORD PTR ?rand_state@@3IA, eax
; Line 14
	pop	ebp
	ret	0
?my_srand@@YAXI@Z ENDP					; my_srand
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
