; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L019\L019\L019.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5556	DB	'a>b', 0aH, 00H
	ORG $+3
$SG5558	DB	'a==b', 0aH, 00H
	ORG $+2
$SG5560	DB	'a<b', 0aH, 00H
	ORG $+3
$SG5566	DB	'a>b', 0aH, 00H
	ORG $+3
$SG5568	DB	'a==b', 0aH, 00H
	ORG $+2
$SG5570	DB	'a<b', 0aH, 00H
	ORG $+3
$SG5573	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?f_singed@@YAXHH@Z				; f_singed
PUBLIC	?f_unsinged@@YAXII@Z				; f_unsinged
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\L019\L019\L019.cpp
; Line 20
	push	ebp
	mov	ebp, esp
; Line 21
	push	OFFSET $SG5573
	call	_printf
	add	esp, 4
; Line 22
	push	2
	push	1
	call	?f_singed@@YAXHH@Z			; f_singed
	add	esp, 8
; Line 23
	push	2
	push	1
	call	?f_unsinged@@YAXII@Z			; f_unsinged
	add	esp, 8
; Line 24
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f_unsinged@@YAXII@Z PROC				; f_unsinged
; File C:\Users\libit\source\repos\L019\L019\L019.cpp
; Line 14
	push	ebp
	mov	ebp, esp
; Line 15
	mov	eax, DWORD PTR _a$[ebp]
	cmp	eax, DWORD PTR _b$[ebp]
	jbe	SHORT $LN2@f_unsinged
	push	OFFSET $SG5566
	call	_printf
	add	esp, 4
$LN2@f_unsinged:
; Line 16
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jne	SHORT $LN3@f_unsinged
	push	OFFSET $SG5568
	call	_printf
	add	esp, 4
$LN3@f_unsinged:
; Line 17
	mov	edx, DWORD PTR _a$[ebp]
	cmp	edx, DWORD PTR _b$[ebp]
	jae	SHORT $LN1@f_unsinged
	push	OFFSET $SG5570
	call	_printf
	add	esp, 4
$LN1@f_unsinged:
; Line 18
	pop	ebp
	ret	0
?f_unsinged@@YAXII@Z ENDP				; f_unsinged
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f_singed@@YAXHH@Z PROC					; f_singed
; File C:\Users\libit\source\repos\L019\L019\L019.cpp
; Line 7
	push	ebp
	mov	ebp, esp
; Line 8
	mov	eax, DWORD PTR _a$[ebp]
	cmp	eax, DWORD PTR _b$[ebp]
	jle	SHORT $LN2@f_singed
	push	OFFSET $SG5556
	call	_printf
	add	esp, 4
$LN2@f_singed:
; Line 9
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jne	SHORT $LN3@f_singed
	push	OFFSET $SG5558
	call	_printf
	add	esp, 4
$LN3@f_singed:
; Line 10
	mov	edx, DWORD PTR _a$[ebp]
	cmp	edx, DWORD PTR _b$[ebp]
	jge	SHORT $LN1@f_singed
	push	OFFSET $SG5560
	call	_printf
	add	esp, 4
$LN1@f_singed:
; Line 11
	pop	ebp
	ret	0
?f_singed@@YAXHH@Z ENDP					; f_singed
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
