; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28720.3 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG30706 DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG30707 DB	'%lld', 0aH, 00H
	ORG $+2
$SG30708 DB	'%I64d', 0aH, 00H
	ORG $+1
$SG30709 DB	'Hello World 1!', 0aH, 00H
$SG30710 DB	'%lld', 0aH, 00H
CONST	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?f@@YA_KXZ					; f
PUBLIC	?f_add@@YA_K_K0@Z				; f_add
PUBLIC	?f_sub@@YA_K_K0@Z				; f_sub
PUBLIC	?f_multi@@YA_K_K0@Z				; f_multi
PUBLIC	?f_div@@YA_K_K0@Z				; f_div
PUBLIC	?f_left@@YA_K_K0@Z				; f_left
PUBLIC	?f_right@@YA_K_K0@Z				; f_right
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+80
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN6
	DD	imagerel $LN6+83
	DD	imagerel $unwind$printf
pdata	ENDS
pdata	SEGMENT
$pdata$main DD	imagerel $LN6
	DD	imagerel $LN6+100
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 041b01H
	DD	07017521bH
	DD	030156016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 081401H
	DD	0a6414H
	DD	095414H
	DD	083414H
	DD	070105214H
xdata	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
main	PROC
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 41
$LN6:
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 42
	lea	rcx, OFFSET FLAT:$SG30706
	call	printf
; Line 45
	mov	rbx, 1311768467294899695		; 1234567890abcdefH
	lea	rcx, OFFSET FLAT:$SG30707
	mov	rdx, rbx
	call	printf
; Line 46
	mov	rdx, rbx
	lea	rcx, OFFSET FLAT:$SG30708
	call	printf
; Line 48
	lea	rcx, OFFSET FLAT:$SG30709
	call	printf
; Line 50
	mov	rdx, 3689348822186520301		; 33333334eeeeeeedH
	lea	rcx, OFFSET FLAT:$SG30710
	call	printf
; Line 51
	xor	eax, eax
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_right@@YA_K_K0@Z PROC				; f_right
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 36
	mov	rax, rcx
; Line 37
	mov	rcx, rdx
	shr	rax, cl
; Line 38
	ret	0
?f_right@@YA_K_K0@Z ENDP				; f_right
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_left@@YA_K_K0@Z PROC					; f_left
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 31
	mov	rax, rcx
; Line 32
	mov	rcx, rdx
	shl	rax, cl
; Line 33
	ret	0
?f_left@@YA_K_K0@Z ENDP					; f_left
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_div@@YA_K_K0@Z PROC					; f_div
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 26
	mov	r8, rdx
; Line 27
	mov	rax, rcx
	xor	edx, edx
	div	r8
; Line 28
	ret	0
?f_div@@YA_K_K0@Z ENDP					; f_div
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_multi@@YA_K_K0@Z PROC				; f_multi
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 22
	imul	rcx, rdx
	mov	rax, rcx
; Line 23
	ret	0
?f_multi@@YA_K_K0@Z ENDP				; f_multi
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_sub@@YA_K_K0@Z PROC					; f_sub
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 17
	sub	rcx, rdx
	mov	rax, rcx
; Line 18
	ret	0
?f_sub@@YA_K_K0@Z ENDP					; f_sub
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_add@@YA_K_K0@Z PROC					; f_add
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 12
	lea	rax, QWORD PTR [rcx+rdx]
; Line 13
	ret	0
?f_add@@YA_K_K0@Z ENDP					; f_add
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?f@@YA_KXZ PROC						; f
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 7
	mov	rax, 1311768467294899695		; 1234567890abcdefH
; Line 8
	ret	0
?f@@YA_KXZ ENDP						; f
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT printf
_TEXT	SEGMENT
_Format$ = 80
printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rcx
; Line 957
	lea	rsi, QWORD PTR _Format$[rsp+8]
; Line 958
	mov	ecx, 1
	call	__acrt_iob_func
	mov	rbx, rax
; Line 643
	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 961
	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx
; Line 643
	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 644
	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 88
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
