; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28720.3 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG30706 DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG30707 DB	'%lld', 0aH, 00H
	ORG $+2
$SG30708 DB	'%I64d', 0aH, 00H
	ORG $+1
$SG30709 DB	'Hello World 1!', 0aH, 00H
$SG30710 DB	'%lld', 0aH, 00H
CONST	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?f@@YA_KXZ					; f
PUBLIC	?f_add@@YA_K_K0@Z				; f_add
PUBLIC	?f_sub@@YA_K_K0@Z				; f_sub
PUBLIC	?f_multi@@YA_K_K0@Z				; f_multi
PUBLIC	?f_div@@YA_K_K0@Z				; f_div
PUBLIC	?f_left@@YA_K_K0@Z				; f_left
PUBLIC	?f_right@@YA_K_K0@Z				; f_right
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3
	DD	imagerel $LN3+87
	DD	imagerel $unwind$printf
pdata	ENDS
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+126
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 011801H
	DD	06218H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 011801H
	DD	06218H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 32
main	PROC
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 41
$LN3:
	sub	rsp, 56					; 00000038H
; Line 42
	lea	rcx, OFFSET FLAT:$SG30706
	call	printf
; Line 44
	call	?f@@YA_KXZ				; f
	mov	QWORD PTR a$[rsp], rax
; Line 45
	mov	rdx, QWORD PTR a$[rsp]
	lea	rcx, OFFSET FLAT:$SG30707
	call	printf
; Line 46
	mov	rdx, QWORD PTR a$[rsp]
	lea	rcx, OFFSET FLAT:$SG30708
	call	printf
; Line 48
	lea	rcx, OFFSET FLAT:$SG30709
	call	printf
; Line 49
	mov	rdx, 2459565879930580718		; 22222222eeeeeeeeH
	mov	rcx, 1229782942255939583		; 11111111ffffffffH
	call	?f_add@@YA_K_K0@Z			; f_add
	mov	QWORD PTR a$[rsp], rax
; Line 50
	mov	rdx, QWORD PTR a$[rsp]
	lea	rcx, OFFSET FLAT:$SG30710
	call	printf
; Line 51
	xor	eax, eax
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_right@@YA_K_K0@Z PROC				; f_right
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 36
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 37
	mov	rax, QWORD PTR b$[rsp]
	movzx	ecx, al
	mov	rax, QWORD PTR a$[rsp]
	shr	rax, cl
; Line 38
	ret	0
?f_right@@YA_K_K0@Z ENDP				; f_right
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_left@@YA_K_K0@Z PROC					; f_left
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 31
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 32
	mov	rax, QWORD PTR b$[rsp]
	movzx	ecx, al
	mov	rax, QWORD PTR a$[rsp]
	shl	rax, cl
; Line 33
	ret	0
?f_left@@YA_K_K0@Z ENDP					; f_left
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_div@@YA_K_K0@Z PROC					; f_div
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 26
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 27
	xor	edx, edx
	mov	rax, QWORD PTR a$[rsp]
	div	QWORD PTR b$[rsp]
; Line 28
	ret	0
?f_div@@YA_K_K0@Z ENDP					; f_div
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_multi@@YA_K_K0@Z PROC				; f_multi
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 21
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 22
	mov	rax, QWORD PTR a$[rsp]
	imul	rax, QWORD PTR b$[rsp]
; Line 23
	ret	0
?f_multi@@YA_K_K0@Z ENDP				; f_multi
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_sub@@YA_K_K0@Z PROC					; f_sub
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 16
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 17
	mov	rax, QWORD PTR b$[rsp]
	mov	rcx, QWORD PTR a$[rsp]
	sub	rcx, rax
	mov	rax, rcx
; Line 18
	ret	0
?f_sub@@YA_K_K0@Z ENDP					; f_sub
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_add@@YA_K_K0@Z PROC					; f_add
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 11
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 12
	mov	rax, QWORD PTR b$[rsp]
	mov	rcx, QWORD PTR a$[rsp]
	add	rcx, rax
	mov	rax, rcx
; Line 13
	ret	0
?f_add@@YA_K_K0@Z ENDP					; f_add
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
?f@@YA_KXZ PROC						; f
; File C:\Users\libit\source\repos\REV_059\REV_059\REV_059.cpp
; Line 7
	mov	rax, 1311768467294899695		; 1234567890abcdefH
; Line 8
	ret	0
?f@@YA_KXZ ENDP						; f
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT printf
_TEXT	SEGMENT
_Result$ = 32
_ArgList$ = 40
_Format$ = 64
printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 56					; 00000038H
; Line 957
	lea	rax, QWORD PTR _Format$[rsp+8]
	mov	QWORD PTR _ArgList$[rsp], rax
; Line 958
	mov	ecx, 1
	call	__acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rsp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rsp]
	mov	rcx, rax
	call	_vfprintf_l
	mov	DWORD PTR _Result$[rsp], eax
; Line 959
	mov	QWORD PTR _ArgList$[rsp], 0
; Line 960
	mov	eax, DWORD PTR _Result$[rsp]
; Line 961
	add	rsp, 56					; 00000038H
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 643
	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rsp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rsp]
	mov	r8, QWORD PTR _Format$[rsp]
	mov	rdx, QWORD PTR _Stream$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 644
	add	rsp, 56					; 00000038H
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 88
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
