; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\L052\L052\L052.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5569	DB	'a=%d,b=%d,c=%d,d=%d', 0aH, 00H
	ORG $+3
$SG5576	DB	'a=%d,b=%d,c=%d,d=%d', 0aH, 00H
	ORG $+3
$SG5581	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?f@@YAXUs@@@Z					; f
PUBLIC	?f1@@YAXDHDH@Z					; f1
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_temp$ = -16						; size = 16
_main	PROC
; File C:\Users\libit\source\repos\L052\L052\L052.cpp
; Line 25
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
; Line 26
	push	OFFSET $SG5581
	call	_printf
	add	esp, 4
; Line 28
	mov	BYTE PTR _temp$[ebp], 1
; Line 29
	mov	DWORD PTR _temp$[ebp+4], 2
; Line 30
	mov	BYTE PTR _temp$[ebp+8], 3
; Line 31
	mov	DWORD PTR _temp$[ebp+12], 4
; Line 32
	sub	esp, 16					; 00000010H
	mov	eax, esp
	mov	ecx, DWORD PTR _temp$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	edx, DWORD PTR _temp$[ebp+4]
	mov	DWORD PTR [eax+4], edx
	mov	ecx, DWORD PTR _temp$[ebp+8]
	mov	DWORD PTR [eax+8], ecx
	mov	edx, DWORD PTR _temp$[ebp+12]
	mov	DWORD PTR [eax+12], edx
	call	?f@@YAXUs@@@Z				; f
	add	esp, 16					; 00000010H
; Line 33
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 1
_b$ = 12						; size = 4
_c$ = 16						; size = 1
_d$ = 20						; size = 4
?f1@@YAXDHDH@Z PROC					; f1
; File C:\Users\libit\source\repos\L052\L052\L052.cpp
; Line 20
	push	ebp
	mov	ebp, esp
; Line 21
	mov	eax, DWORD PTR _d$[ebp]
	push	eax
	movsx	ecx, BYTE PTR _c$[ebp]
	push	ecx
	mov	edx, DWORD PTR _b$[ebp]
	push	edx
	movsx	eax, BYTE PTR _a$[ebp]
	push	eax
	push	OFFSET $SG5576
	call	_printf
	add	esp, 20					; 00000014H
; Line 22
	pop	ebp
	ret	0
?f1@@YAXDHDH@Z ENDP					; f1
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_s1$ = 8						; size = 16
?f@@YAXUs@@@Z PROC					; f
; File C:\Users\libit\source\repos\L052\L052\L052.cpp
; Line 15
	push	ebp
	mov	ebp, esp
; Line 16
	mov	eax, DWORD PTR _s1$[ebp+12]
	push	eax
	movsx	ecx, BYTE PTR _s1$[ebp+8]
	push	ecx
	mov	edx, DWORD PTR _s1$[ebp+4]
	push	edx
	movsx	eax, BYTE PTR _s1$[ebp]
	push	eax
	push	OFFSET $SG5569
	call	_printf
	add	esp, 20					; 00000014H
; Line 17
	pop	ebp
	ret	0
?f@@YAXUs@@@Z ENDP					; f
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 954
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 957
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 958
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 959
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 960
	mov	eax, DWORD PTR __Result$[ebp]
; Line 961
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
; Line 642
	push	ebp
	mov	ebp, esp
; Line 643
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 644
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
; Line 86
	push	ebp
	mov	ebp, esp
; Line 88
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 89
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
